spring:
  # 数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zero-admin?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 3
      read-only: false
  redis:
    host: 127.0.0.1
    port: 6379
  # rabbitmq连接配置信息
#  rabbitmq:
#    host: ${SPRING_RABBITMQ_HOST}
#    host: ${SPRING_RABBITMQ_HOST}
#    #端口默认就是5672，如果没有RabbitMQ没有修改默认端口的话，可以不配置
#    port: 5672
#    virtual-host: /zero-admin
#    username: root
#    password: admin
  #  devtools:
  #    restart:
  #      enabled: true  #设置开启热部署
  #      additional-paths: src/main/java #重启目录
  web:
    resources:
      # 访问系统外部资源，将该目录下的文件映射到系统下
      static-locations: file:F:\tmp\
zero:
  domain-name: http://127.0.0.1:10000
  vue-domain: http://127.0.0.1:20000
  auth:
    security:
      jwt:
        rsa:
          private-file: F:\\tmp\\rsa\\rsa.pri
          public-file: F:\\tmp\\rsa\\rsa.pub
  common:
    # Swagger文档配置
    swagger:
      # 是否启用Swagger文档
      enable: true
  upload:
    # 文件上传目标路径
    path: F:\tmp\
logging:
  config: classpath:logback-spring-dev.xml
