server:
  # 项目启动端口
  port: 10000
  # 项目请求前缀
  servlet:
    context-path: /api
  # tomcat字符编码
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    # Spring应用名称
    name: zero-admin
  # Jackson相关配置
  jackson:
    # 常用，全局设置实体类或被@JsonInclude注解的属性的序列化方式
    default-property-inclusion: ALWAYS
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
    pathmatch:
      matching-strategy: ant_path_matcher
  # SpringMail发送邮件相关配置
  mail:
    # 发送邮件的账号名
    username: ${SPRING_MAIL_USERNAME}
    # 授权码
    password: ${SPRING_MAIL_PASSWORD}
    # smtp服务主机  qq邮箱的服务主机为smtp.qq.com
    host: smtp.qq.com
    # 服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    # 服务端口
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: jakarta.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
  freemarker:
    charset: UTF-8
    template-loader-path: classpath:/templates/
    content-type: text/html
    suffix: .ftlh
    prefer-file-system-access: false
  # 动态配置文件后缀
  profiles:
    active: dev
# MyBatisPlus的相关配置
mybatis-plus:
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
    # 打印sql语句，将mybatis-plus自带的SQL打印注释，使用logback记录日志
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 需要配置该处理器，才会使用@EnumValue注解的值持久化到数据库中
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  # 配置逻辑删除字段
  global-config:
    db-config:
      # 删除状态为1(true)
      logic-delete-value: true
      # 没有删除状态为0(false)
      logic-not-delete-value: false
  # 枚举类型包
  type-enums-package: com.zero.*.enums
  mapper-locations: classpath*:/com/zero/*/mapper/*.xml
zero:
  api-path: ${zero.domain-name}${server.servlet.context-path}
  auth:
    user:
      # root用户默认用户名
      root-username: root
      # root用户默认密码
      root-password: 111111
      # 普通用户默认密码
      default-password: 111111
    role:
      # root角色默认角色名
      root-name: root
      # root角色默认描述信息
      root-description: root权限，系统的最高权限
    security:
      jwt:
        ttl: 3600000
        issuer: ${zero.domain-name}
        key: accessToken
        rsa:
          secret: HdGkiOiI4ODgiLCJzdWIiOiLlsIdkdusdmnwlsYdfDSkpqlzelqJhdSKDxljHlNKKjds
    oauth:
      target-origin-key: targetOrigin
      message-page: oauth-login
      github:
        client-id: ${ZERO_AUTH_OAUTH_GITHUB_CLIENT_ID}
        client-secrets: ${ZERO_AUTH_OAUTH_GITHUB_CLIENT_SECRETS}
        token_url: https://github.com/login/oauth/access_token?client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&code={CODE}
        token_name: access_token
        user_info_url: https://api.github.com/user
  # 邮件模板内容
  mail:
    template:
      verify:
        # 邮箱验证码redisKey前缀
        key: mail:verify
        # 邮箱验证码长度
        length: 6
        # 邮箱验证码有效时长
        ttl: 300000
        # 邮箱验证码邮件主题
        subject: 邮箱验证码
        # 邮箱验证码邮件模板路径
        path: /templates/mail
        # 邮箱验证码邮件模板文件
        file: verify.ftlh
      login-mail:
        # 登录邮件主题
        subject: 系统账号登录
        # 登录邮箱邮件模板路径
        path: /templates/mail
        # 登录邮箱邮件模板文件
        file: login-mail.ftlh
  # 文件上传通用的配置信息
  upload:
    # 备份文件后缀
    bak-suffix: bak
    # 默认的文件类型
    default-file:
      # 默认的文件类型上传目标路径
      path: default
      # 默认的文件类型上传允许的类型
      allowTypes:
    image:
      # 图片文件上传目标路径
      path: image
      # 图片文件上传允许的类型
      allowTypes:
        - image/jpeg
        - image/png
    http:
      third:
        api:
          enable-ip-info: false
          ip-info: https://ip.taobao.com/outGetIpInfo?accessKey=alibaba-inc&ip=
          weather-info: http://wthrcdn.etouch.cn/weather_mini?city=


