### 发送一个PSOT请求，获取token，并将token设置为全局变量
POST http://127.0.0.1:10000/api/login?username=user&password=111111
Accept: application/json

> {% client.global.set("accessToken", response.body.data); %}

### 分页获取用户数据
GET http://127.0.0.1:10000/api/user/page/1?size=10
accessToken: {{accessToken}}
Accept: application/json

###
GET http://127.0.0.1:10000/api/user/check/password?password=111111
accessToken: {{accessToken}}
Accept: application/json

###